name 'opsworks_nodejs'
maintainer 'Maksim Aniskov'
maintainer_email 'MaksimAniskov@gmail.com'
license 'MIT'
description 'Installs/Configures opsworks_nodejs'
long_description 'Installs/Configures opsworks_nodejs'
version '0.1.0'
chef_version '~> 12'
depends 'git', '~> 9.0.1'
depends 's3_cli', '~> 1.0.2'
depends 'zipfile', '~> 0.2.0'
depends 'nodejs', '~> 8.12.0'

issues_url 'https://github.com/maksimaniskov/opsworks_nodejs/issues'

source_url 'https://github.com/maksimaniskov/opsworks_nodejs'
